const dummyMovies = [
  {
    id: 1,
    title: "Inception",
    year: 2010,
    rating: 4.8,
    genre: "Sci-Fi",
    poster: "https://m.media-amazon.com/images/I/51v5ZpFyaFL._AC_.jpg",
  },
  {
    id: 2,
    title: "Interstellar",
    year: 2014,
    rating: 4.6,
    genre: "Action",
    poster: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
  },
  {
    id: 3,
    title: "The Matrix",
    year: 1999,
    rating: 4.7,
    genre: "Thriller",
    poster: "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
  },
  {
    id: 4,
    title: "Avatar",
    year: 2009,
    rating: 4.5,
    genre: "Romance",
    poster: "https://m.media-amazon.com/images/I/41kTVLeW1CL._AC_.jpg",
  },
  {
    id: 5,
    title: "Inception",
    year: 2010,
    rating: 4.8,
    genre: "Drama",
    poster: "https://m.media-amazon.com/images/I/51v5ZpFyaFL._AC_.jpg",
  },
  {
    id: 6,
    title: "Interstellar",
    year: 2014,
    rating: 4.6,
    genre: "Sci-Fi",
    poster: "https://m.media-amazon.com/images/I/71niXI3lxlL._AC_SY679_.jpg",
  },
  {
    id: 7,
    title: "The Matrix",
    year: 1999,
    rating: 4.7,
    genre: "Sci-Fi",
    poster: "https://m.media-amazon.com/images/I/51EG732BV3L.jpg",
  },
  {
    id: 8,
    title: "Avatar",
    year: 2009,
    rating: 4.5,
    genre: "Action",
    poster: "https://m.media-amazon.com/images/I/41kTVLeW1CL._AC_.jpg",
  },
];

export default dummyMovies;
